### ISSUE TITLE
Cannot find services

### ISSUE THREAD

**Issue by SwatGuard** [AlTavares/Ciao#4]
I'm trying to find services using the following code :

`
 func scanCiao(){
        let ciaoBrowser = CiaoBrowser()
        
        ciaoBrowser.browse(type: "_hap._tcp.") { service in
            print(service)
            print(service.txtRecordDictionary)
         print(service.hostName)
        }
`
But all i get in the console is: 

`2018-06-27 03:32:19391 [info][CiaoBrowser.swift]:103 netServiceBrowserWillSearch -> "Browser will search"
2018-06-27 03:32:19398 [info][CiaoBrowser.swift]:22 isSearching -> true`

I have lots of services running and I can "see" them with a bonjour browsing app.

What am I doing wrong ? 

Thanks in advance!

**Comment by AlTavares** [comment]
Hi @SwatGuard 

That's a bit weird...
Did you try using the service type enum init?
`ciaoBrowser.browse(type: ServiceType.tcp("hap"))`

Also, you could try using this(only for debugging):
`ciaoBrowser.browse(type: "_services._dns-sd._udp")`
it should print any service it finds, although it will give some resolving errors that I'll be releasing a fix soon in the next version.

Cheers!
