### ISSUE TITLE
Is there a client/peer limit to Ciao and does is allow users to connect and share data with each other?

### ISSUE THREAD

**Issue by lsamaria** [AlTavares/Ciao#5]
Hello,

I wanted to use the Multipeer Connectivity framework but there is a limit of 8 peers per session. That isn't ideal for my app. I came across a post on apple developer (photo below) that said it's possible to go beyond that limit using Bonjour and I came across Ciao.

Using Ciao is it possible for users of the app to connect with one another and to share data?

How many users does Ciao allow to connect with each other?

If there is a limit can it be increased?

![Screen Shot 2020-02-22 at 12 50 10 AM](https://user-images.githubusercontent.com/15787990/75089809-9aa95f00-552a-11ea-9035-fff22243d478.png)

**Comment by AlTavares** [comment]
Hello!
Ciao is designed only to publish and discover bonjour services, for the actual connection you have to use something else, like WebSockets.

**Comment by lsamaria** [comment]
Hi, thanks for getting back to me! I know zero about networking but once I realized the MultiConnectivity was limited and I found that post above I said to myself that's the way I need to go. I've been googling around for hours gathering information and I saw something about WebSockets but I don't know what that is. I have to do more research. I do know this pod `CocoaAsyncSocket` is supposed to make it 1000x easier. I just have to figure out how to hook it all up.

Thanks for the reply!

**Comment by AlTavares** [comment]
You're welcome :) 
Also, if you are targetting only iOS 13+ you should take a look at [URLSessionWebSocketTask](https://developer.apple.com/documentation/foundation/urlsessionwebsockettask)

**Comment by lsamaria** [comment]
Hi,

There are too many users on iOS 12 so I have to cater to the largest audience and do what's best for them. Thanks for the link to URLSessionWebSocketTask. I have no idea how to use it but I'll look into it when I decide to change to iOS13.

Cheers!
